### ISSUE TITLE
wwww

### ISSUE THREAD

**Issue by Hoffs** [microsoft/wslg#225]
Win32 API (clipboard) errors within desktop entry WSLg terminal crashing GUI app

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21387.1]
Your Distribution version: Debian 10
Your WSLg version: 
WSLg ( x86_64 ): 1.0.22+Branch.main.Sha.d7102a7ff8a3bb04bbcd3483c3f7d7a7633686a1
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 9e402088aa2cd9316851ea20b9befbcf3b9c9564
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

# Steps to reproduce

I replicated this in various terminals, different distros and neovim when configured with win32yank.exe. Simplest method:

- Start Ubuntu
- Install xterm (`sudo apt install xterm`). This terminal adds desktop entries itself, so no need to do it manually.
- Dowload `win32yank.exe` as per https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
```
curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
chmod +x /tmp/win32yank.exe
```
- Start xterm using desktop entry from Windows (I start XTerm, not UXTerm)
- In xterm window do `echo "test" | /tmp/win32yank.exe -i` (might need to do mutiple times)

This sequence is not guaranteed to always crash but it eventually does. I observed 3 outcomes:
1. Executes without any obvious errors
2. Executes but then terminal seems to keep starting/sourcing until user input is received, as in:
```none
hoffs@LUJON:~$ echo "test" | /tmp/win32yank.exe -i                                                                      
hoffs@LUJON:~$                                                                                                          
hoffs@LUJON:~$                                                                                                          
hoffs@LUJON:~$                                                                                                          
hoffs@LUJON:~$                                                                                                          
hoffs@LUJON:~$ 
```
3. Straight up crashes/closes the terminal/window

Sometimes it also looks like a window inside Windows gets opened and immediately closed (similarly to how it used to be before https://github.com/microsoft/wslg/issues/64).
Sometimes the window also just hangs.

Also it only happens when copying to the clipboard and not getting from the clipboard (`win32yank.exe -i` for copy to clipboard from stdin and `win32yank.exe -o` for output from clipboard).

Executing same sequence of events when xterm is started from ubuntu terminal and not desktop entry does not have these issues:
```none
cmd> ubuntu
ubuntu> xterm
xterm> echo "test" | /tmp/win32yank.exe -i
```

**WSL logs**: 

I could not find any way to get any useful logs.

Nothing relevant is logged in file logs.

etl file also does not look like it captures anything useful

neovim logs when executing win32yank.exe (same sequence as in https://github.com/microsoft/wslg/issues/15#issuecomment-836874515)
```
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(1418)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(5)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 
```

#  Expected behavior

Text gets yanked and nothing bad happens.

# Actual behavior

Win32 API errors with possibility for the whole WSLg window to close.

Seems similar to https://github.com/microsoft/wslg/issues/64

Not sure how relevant this is, but the fact that issues only exist when the application is started using desktop entry seems like it might be an actual issue.

**Comment by sanchit1053** [comment]
I am also getting this error, though the copy and paste works, 
Is there any solution?
