### ISSUE TITLE
Could not open playback device 'default': No such file or directory

### ISSUE THREAD

**Issue by 0smile** [microsoft/wslg#634]
### Version

Microsoft Windows [版本 10.0.22000.376]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

gazebo 11

### Repro Steps

run gazebo.

### Expected Behavior

Gazebo should show 3d simulation world in the right windows.

### Actual Behavior

Gazebo only show gray background, no 3d object.

Output from teminal:

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory

### Diagnostic Logs

I'm using a intel Xe graphic with latest driver.

**Comment by hideyukn88** [comment]
@0smile, thanks for reporting the issue. I believe this could be same issue as https://github.com/microsoft/wslg/issues/455, thanks!

**Comment by bprentice77** [comment]
I receive this same error in the terminal when trying to run a rust-lang program with dependencies on libsdl2-dev and libasound2-dev.

`ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /home/brett/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.11.0/src/engine.rs:149:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by philippmossier** [comment]
> I receive this same error in the terminal when trying to run a rust-lang program with dependencies on libsdl2-dev and libasound2-dev.
> 
> `ALSA lib confmisc.c:767:(parse_card) cannot find card '0' ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /home/brett/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.11.0/src/engine.rs:149:14 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

same problem with rust and wsl2

**Comment by jonaskuske** [comment]
Had the same problem with sound playback in Epiphany / GNOME Web, but managed to fix it:

1. Create `~/.asoundrc` so ALSA uses WSLg's PulseAudio server as default "sound card":

```
pcm.default pulse
ctl.default pulse
```

2. Change the `PULSE_SERVER` env variable to include the `unix:` scheme:

```bash
export PULSE_SERVER=unix:$PULSE_SERVER
```

And now it should work, at least it did for me :)

**Comment by TonalidadeHidrica** [comment]
@jonaskuske Hi, I have encountered a same issue and I could not resolve it with your way.  Using Ubuntu 22.04.  I'd be appreciated if you could give me some idea.

I prepended `unix:` to `PULSE_SERVER` environment:
```
$ export | grep PULSE_SERVER
PULSE_SERVER unix:/mnt/wslg/PulseServer
```

Without `~/.asoundrc`:
``2`
$ cat ~/.asoundrc
# pcm.default pulse
# ctl.default pulse

$ run_my_program_that_acceses_alsa
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
```

After modifying `~/.asoundrc`:
```
$ cat ~/.asoundrc
pcm.default pulse
ctl.default pulse

$ run_my_program_that_acceses_alsa

ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM pulse
```

Could it be due to a bug of WSLg, a misconfiguration, or a bug in my program?  Do you have any idea what does the error mean, why does the program does not respect `$PULSE_SERVER` and how could I make it recognize?
At least, I have succeeded in playing sound with `ffplay` in WSL2.

**Comment by TonalidadeHidrica** [comment]
I found a resolution, which I described in #864 .  Actually, I didn't need to modify `$PULSE_SERVER`.  Instead, I needed to install an additional PulseAudio plugin, which I described in #864 .
