### ISSUE TITLE
[Feature Request] Expose the XWayland process to system monitor (e.g., `ps`, `top`, `htop`)

### ISSUE THREAD

**Issue by XuehaiPan** [microsoft/wslg#919]
### Is your feature request related to a problem:

While using the `nvitop` to monitor the NVIDIA GPU usage in WSL, it cannot retrieve the process info returned from the NVIDIA driver.

```bash
$ nvitop -1
Sat Dec 10 12:35:33 2022
╒═════════════════════════════════════════════════════════════════════════════╕
│ NVITOP 0.11.0        Driver Version: 526.98       CUDA Driver Version: 12.0 │
├───────────────────────────────┬──────────────────────┬──────────────────────┤
│ GPU  Name        Persistence-M│ Bus-Id        Disp.A │ Volatile Uncorr. ECC │
│ Fan  Temp  Perf  Pwr:Usage/Cap│         Memory-Usage │ GPU-Util  Compute M. │
╞═══════════════════════════════╪══════════════════════╪══════════════════════╪════════════════════╕
│   0  GeForce RTX 3070    On   │ 00000000:09:00.0  On │                  N/A │ MEM: ███▏ 34.7%    │
│  0%   55C    P3    30W / 240W │    2844MiB / 8192MiB │     49%      Default │ UTL: ████▍ 49%     │
╘═══════════════════════════════╧══════════════════════╧══════════════════════╧════════════════════╛
[ CPU: █▌ 3.1%                                                ]  ( Load Average:  0.08  0.02  0.01 )
[ MEM: ██▎ 4.5%                                               ]  [ SWP: ▏ 0.0%                     ]

╒══════════════════════════════════════════════════════════════════════════════════════════════════╕
│ Processes:                                                       PanXuehai@BIGAI-PanXuehai (WSL) │
│ GPU     PID      USER  GPU-MEM %SM  %CPU  %MEM  TIME  COMMAND                                    │
╞══════════════════════════════════════════════════════════════════════════════════════════════════╡
│   0      23 G     N/A WDDM:N/A N/A   N/A   N/A   N/A  No Such Process                            │
╘══════════════════════════════════════════════════════════════════════════════════════════════════╛

$ nvidia-smi
Sat Dec 10 20:36:09 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.02    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:09:00.0  On |                  N/A |
|  0%   56C    P3    34W / 240W |   2880MiB /  8192MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
```

The `/Xwayland` process is not available in the `/proc` directory. Users cannot monitor this process via process utilities, such as `ps`, `top`, `htop` and `psutil`.

```console
$ /bin/ls /proc/23
/bin/ls: cannot access '/proc/23': No such file or directory

$ python3 -c 'import psutil; print(psutil.Process(pid=23))'
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_common.py", line 446, in wrapper
    return fun(self)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_pslinux.py", line 1687, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_common.py", line 776, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_common.py", line 764, in cat
    with _open(fname) as f:
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_common.py", line 728, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/23/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_pslinux.py", line 1855, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/_pslinux.py", line 1652, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=23)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=23)
```

### Describe the solution you'd like:

Make the `/Xwayland` process detectable to Linux process utilities.

### Describe alternatives you've considered:

Put the PID of `/Xwayland` in a readable file. Then the downstream libraries can add some `if-else` branch to handle the issue described above.

**Comment by Biswa96** [comment]
You may access that PID from system distribution i.e. try wsl.exe --system` command.

**Comment by XuehaiPan** [comment]
> You may access that PID from system distribution i.e. try `wsl.exe --system` command.

@Biswa96 Thanks for the quick reply. It works but it starts a new shell with distro `CBL-Marner` with a completely different runtime environment than the user distribution. Can those processes be accessed in the user distro?

**Comment by Biswa96** [comment]
> Can those processes be accessed in the user distro?

As far as I know, those can not be access in user distribution. Every distribution starts with different PID namespace. Fore more information, see CLONE_NEWPID in `man 2 clone`.

**Comment by XuehaiPan** [comment]
> As far as I know, those can not be access in user distribution. Every distribution starts with different PID namespace.

Thanks for the clarification.

**Comment by XuehaiPan** [comment]
> Every distribution starts with different PID namespace.

Confirm that the PID namespace is not shared. See PID 9 below.

```console
$ ps -auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2276  1532 ?        Sl   19:58   0:00 /init
root         4  0.0  0.0   2276     4 ?        Sl   19:58   0:00 plan9 --control-socket 5 --log-level 4 --server-fd 6 --pipe-fd 8 --log-truncate
root         7  0.0  0.0   2292   100 ?        Ss   19:58   0:00 /init
root         8  0.0  0.0   2292   108 ?        S    19:58   0:00  \_ /init
PanXueh+     9  0.3  0.0  16988 11392 pts/0    Ss   19:58   0:01      \_ -zsh
PanXueh+  1065  0.0  0.0   9140  3292 pts/0    R+   20:04   0:00      |   \_ ps -auxf
PanXueh+   334  0.0  0.0  13760  5032 pts/0    S    19:58   0:00      \_ -zsh
PanXueh+   348  0.0  0.0   2900  1256 pts/0    Sl   19:58   0:00          \_ /home/PanXuehai/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.4 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 4

$ wsl.exe --system ps -auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2276  1532 ?        Sl   19:58   0:00 /init
root         2  0.0  0.0   2276  1532 ?        Sl   19:58   0:00 /init
root        13  0.0  0.0   2276     4 ?        Sl   19:58   0:00  \_ plan9 --control-socket 5 --log-level 4 --server-fd 6 --pipe-fd 8 --log-truncate
root        16  0.0  0.0   2292   100 ?        Ss   19:58   0:00  \_ /init
root        17  0.0  0.0   2292   108 ?        S    19:58   0:00      \_ /init
wslg        18  0.2  0.0  16988 11392 pts/0    Ss   19:58   0:01          \_ -zsh
wslg      1147  0.0  0.0   2160  1600 pts/0    S+   20:05   0:00          |   \_ /init /mnt/c/Windows/system32/wsl.exe wsl.exe --system ps -auxf
wslg       352  0.0  0.0  13760  5032 pts/0    S    19:58   0:00          \_ -zsh
wslg       379  0.0  0.0   2900  1256 pts/0    Sl   19:58   0:00              \_ /home/PanXuehai/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.4 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 4
root         6  0.0  0.0 121568  8572 ?        Sl   19:58   0:00 /usr/bin/WSLGd
wslg         9  0.0  0.1 961336 40496 ?        Sl   19:58   0:00  \_ /usr/bin/weston --backend=rdp-backend.so --modules=wslgd-notify.so --xwayland --log=/mnt/wslg/weston.log --socket=wayland-0 --shell=rdprail-shell.so --logger-scopes=log,rdp-backend,rdprail-shell
wslg        12  0.0  0.0  18464  8472 ?        Ss   19:58   0:00  |   \_ /usr/libexec/weston-rdprail-shell
wslg       269  0.0  0.2 310868 52224 ?        Ssl  19:58   0:00  |   \_ /usr/bin/Xwayland :0 -rootless -core -listen 38 -wm 39 -terminate -nolisten local -ac
wslg       364  0.0  0.0   2152  1592 ?        S    19:58   0:00  \_ /init /mnt/c/Users/PanXuehai/AppData/Local/Microsoft/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe/msrdc.exe /mnt/c/Users/PanXuehai/AppData/Local/Microsoft/WindowsApps/Micro
message+   365  0.0  0.0   8616  4116 ?        S    19:58   0:00  \_ /usr/bin/dbus-daemon --syslog --nofork --nopidfile --system
wslg       366  0.0  0.0 234480  7976 ?        Sl   19:58   0:00  \_ /usr/bin/pulseaudio --log-target=file:/mnt/wslg/pulseaudio.log --load=module-rdp-sink sink_name=RDPSink --load=module-rdp-source source_name=RDPSource --load=module-native-protocol-unix socket=/mnt/wsl
wslg       370  0.0  0.0   8484   356 ?        Ss   19:58   0:00 /usr/bin/dbus-daemon --syslog --fork --print-pid 13 --print-address 15 --session
root      1148  0.0  0.0   2292   100 ?        Ss   20:05   0:00 /init
root      1149  0.0  0.0   2292   108 ?        S    20:05   0:00  \_ /init
wslg      1150  0.0  0.0   6400  1168 pts/0    Rs+  20:05   0:00      \_ ps -auxf
```
