### ISSUE TITLE
Fresh Win11 & Fresh WSL2 Ubuntu install, no X apps work, Xwayland process runaway (Nvidia)

### ISSUE THREAD

**Issue by xasmodeanx** [microsoft/wslg#993]
### Windows build number:

Microsoft Windows [Version 10.0.22621.1265]

### Your Distribution version:

Ubuntu 22.04

### Your WSL versions:

C:\Users\xasmo>wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1265

### Steps to reproduce:

1. Install Windows 11
2. Install Nvidia drivers
3. reboot
4. Install/Configure WSL2 per https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
5. reboot
6. Install Ubuntu in WSL2 with `wsl --install Ubuntu`
7. Launch Ubuntu
8. Configure first time username/password
9. `sudo apt update`
10. `sudo apt install x11-apps`
11. `xeyes` - observe that xeyes attempts to launch, but hangs, no GUI window ever appears, and no message appears

### WSL logs:

[stderr.log](https://github.com/microsoft/wslg/files/10841765/stderr.log)
[versions.txt](https://github.com/microsoft/wslg/files/10841766/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/10841767/weston.log)
[wlog.log](https://github.com/microsoft/wslg/files/10841768/wlog.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/10841769/pulseaudio.log)

### WSL dumps:

No dumps generated

### Expected behavior:

`xeyes` launches and a new window appears in Windows containing the xeyes GUI application

### Actual behavior:

`xeyes` and all other X11/Wayland apps attempt to launch but either hang or never attach to any socket suitable for displaying graphical windows.  Opening `wsl --system` and then `top` shows that process  `/usr/bin/Xwayland :0 -rootless -core -listen 38 -wm 39 -terminate -nolisten local -ac` is pegging one CPU core at 100%

### Show GPU hardware in Ubuntu
`nvidia-smi`:
> Sun Feb 26 21:30:18 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:00:09.0  On |                  N/A |
| 29%   33C    P8    20W / 250W |   1494MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

**Notice that Nvidia GPU card is correctly identified and we even see the XWayland process running**

### strace
`strace -ff xeyes` : 
> sysinfo({uptime=1668, loads=[65536, 65536, 58304], totalram=25200570368, freeram=24596684800, sharedram=2478080, bufferram=24899584, totalswap=6442450944, freeswap=6442450944, procs=187, totalhigh=0, freehigh=0, mem_unit=1}) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110

**Notice strace appears to hang on the last line forever**

### Xwayland is running away
From Elevated cmd: `wsl --system`, then `top`
![image](https://user-images.githubusercontent.com/50801917/221474883-2ea3b0a1-e6bc-4a9c-8b43-1eedfdbf72dd.png)

**Xwayland process starts immediately after `wsl --shutdown` and a re-launch of Ubuntu, even without attempting to run a GUI app in Ubuntu, xwayland will peg 100% cpu after about 2 seconds**

### /tmp/.X11-unix is mounted and shared with WSL core
`mount | grep .X11`:
> none on /tmp/.X11-unix type tmpfs (ro,relatime)

`touch /tmp/.X11-unix/something`
`ls -lah /tmp/.X11-unix`
> total 4.0K
drwxrwxrwx 2 root       root         80 Feb 26 21:00 .
drwxrwxrwt 3 root       root       4.0K Feb 26 20:47 ..
srwxrwxrwx 1 xasmodeanx xasmodeanx    0 Feb 26 20:58 X0
-rw-r--r-- 1 root       root          0 Feb 26 21:00 something

`ls -lah /mnt/wslg/.X11-unix`
> total 0
drwxrwxrwx 2 root       root        80 Feb 26 21:00 .
drwxrwxrwt 7 root       root       280 Feb 26 20:58 ..
srwxrwxrwx 1 xasmodeanx xasmodeanx   0 Feb 26 20:58 X0
-rw-r--r-- 1 root       root         0 Feb 26 21:00 something

**`wsl --system` shows we can read/write files between Ubuntu and WSL Core**

### Ubuntu environment variables are unremarkable
`printenv`
> SHELL=/bin/bash
WSL2_GUI_APPS_ENABLED=1
WSL_DISTRO_NAME=Ubuntu
NAME=win11gaming
PWD=/tmp/.X11-unix
LOGNAME=xasmodeanx
HOME=/home/xasmodeanx
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/9_interop
LS_COLORS=...
WAYLAND_DISPLAY=wayland-0
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=xasmodeanx
DISPLAY=:0
SHLVL=1
XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/xasmo/AppData/Local/Microsoft/WindowsApps:/snap/bin
HOSTTYPE=x86_64
PULSE_SERVER=/mnt/wslg/PulseServer
OLDPWD=/home/xasmodeanx
_=/usr/bin/printenv

### Other diagnostic info
`cat /mnt/wslg/versions.txt`
> WSLg ( x86_64 ): 1.0.47+Branch.main.Sha.77aa1e2f49e1253cde9ceb9124ca0873eb3eadf2
Mariner: VERSION="2.0.20221010"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: e7e91e17f370702f386c843cf9014cc4bcef4179

**Comment by xasmodeanx** [comment]
I didn't know if this was a WSL or WSLg bug, so I cross-filed it at https://github.com/microsoft/WSL/issues/9701, sorry if that was not right.

**Comment by xasmodeanx** [comment]
wsl prompted for an update today, i ran wsl --update and wsl --shutdown, then restarted things.  Same behavior with an out of control Xwayland process, and nothing can attach to the /tmp/.X11-unix/X0 socket.

**Comment by wesseli01** [comment]
Hi, My situaiton is the same! The links are missing. 
WSL-Version: 1.1.3.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.49
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22621.1344

**Comment by hideyukn88** [comment]
@xasmodeanx , thanks for repoting the issue, would you please collect core dump of Xwayland when it's using 100% of CPU? thanks!

1: From Windows's command prompt, run wsl --system -u root. if you have multiple distro installed and it occurs with your non-default distro, you will need to add -d [your distro name from wsl --list] option.
2: It launch bash in system-distro, type tdnf install gdb
3: then find pid of /usr/bin/Xwayland from ps -aux
4: then gcore [Xwayland's pid]
5: please share generated core file with us.

**Comment by xasmodeanx** [comment]
@hideyukn88, per your instructions, the core file for Xwayland is attached.
[core.zip](https://github.com/microsoft/wslg/files/10937949/core.zip)

**Comment by Stary2001** [comment]
I've also got this issue. I have a Nvidia GTX 1060, and the game ready driver version 546.33.

wsl --version:
```WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2861```

Backtrace:
```#0  0x00007f6c877c7c8a in __memset_avx2_unaligned_erms () from /lib/libc.so.6
#1  0x00007f6c828e172e in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#2  0x00007f6c83d7f75f in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#3  0x00007f6c828def09 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#4  0x00007f6c828dfe1e in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#5  0x00007f6c82884ec5 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#6  0x00007f6c827e2350 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#7  0x00007f6c82737552 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#8  0x00007f6c827d8b22 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#9  0x00007f6c83e63c7d in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#10 0x00007f6c83e645aa in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#11 0x00007f6c84012044 in ?? () from /usr/lib/wsl/drivers/nv_dispig.inf_amd64_866484083fc526af/libnvwgf2umx.so
#12 0x00007f6c858b5910 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#13 0x00007f6c858f3a75 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#14 0x00007f6c857ec3e9 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#15 0x00007f6c85cc501b in ?? () from /usr/lib/wsl/lib/libd3d12.so
#16 0x00007f6c85cc6e18 in ?? () from /usr/lib/wsl/lib/libd3d12.so
#17 0x00007f6c85cc6c87 in ?? () from /usr/lib/wsl/lib/libd3d12.so
#18 0x00007f6c85cc61c6 in ?? () from /usr/lib/wsl/lib/libd3d12.so
#19 0x00007f6c857e00af in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#20 0x00007f6c857e2634 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#21 0x00007f6c857e2e40 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#22 0x00007f6c8579b963 in ?? () from /usr/lib/wsl/lib/libd3d12core.so
#23 0x00007f6c8686a532 in d3d12_init_screen(d3d12_screen*, IUnknown*) () from /usr/lib/dri/swrast_dri.so
#24 0x00007f6c868691d1 in d3d12_init_dxcore_screen(d3d12_screen*) () from /usr/lib/dri/swrast_dri.so
#25 0x00007f6c86869417 in d3d12_create_dxcore_screen () from /usr/lib/dri/swrast_dri.so
#26 0x00007f6c8607208a in sw_screen_create_vk () from /usr/lib/dri/swrast_dri.so
#27 0x00007f6c86840057 in pipe_loader_sw_create_screen () from /usr/lib/dri/swrast_dri.so
#28 0x00007f6c8683ff76 in pipe_loader_create_screen () from /usr/lib/dri/swrast_dri.so```
Core:
[core.zip](https://github.com/microsoft/wslg/files/13774024/core.zip)
